version: "3.9"
services:
  rev_proxy:
    build:
      context: "./"
      dockerfile: "nginx.df"
    container_name: "rev_proxy"
    ports:
      - "80:80"
    networks:
      - "frontend_bridge"
      - "backend_bridge"
    depends_on:
      - "frontend"
      - "backend"

  frontend:
    build:
      context: "./"
      dockerfile: "frontend.df"
    container_name: "frontend"
    networks:
      - "frontend_bridge"
    expose:
      - "3000"

  backend:
    build:
      context: "./"
      dockerfile: "backend.df"
    container_name: "backend"
    environment:
      - DB1_NAME
      - DB2_NAME
    networks:
      - "backend_bridge"
      - "db_cluster"
    depends_on:
      - "db2"
    expose:
      - "4000"

  db1:
    build:
      context: "./"
      dockerfile: db.df
    container_name: $DB1_NAME
    networks:
      - "db_cluster"
    volumes:
      - "cass-shared:/var/lib/cassandra/data"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160

  db2:
    build:
      context: "./"
      dockerfile: db.df
    container_name: $DB2_NAME
    networks:
      - "db_cluster"
    #volumes:
    #  - "cass-shared2:/var/lib/cassandra/data"
    depends_on:
      - $DB1_NAME
    environment:
      - CASSANDRA_SEEDS=$DB1_NAME,$DB2_NAME
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160

networks:
  frontend_bridge:
    driver: "bridge"
    attachable: true

  backend_bridge:
    driver: "bridge"
    attachable: true

  db_cluster:
    driver: "bridge"
    attachable: true

volumes:
  cass-shared:
    driver: "local"
    name: "cass-shared"
