version: "3.9"
services:
  rev_proxy:
    build:
      context: "./"
      dockerfile: "nginx.df"
    container_name: "rev_proxy"
    ports:
      - "80:80"
    networks:
      - "frontend_bridge"
      - "backend_bridge"
    depends_on:
      - "frontend"
      - "backend"

  frontend:
    build:
      context: "./"
      dockerfile: "frontend.df"
    container_name: "frontend"
    networks:
      - "frontend_bridge"
    expose:
      - "3000"

  backend:
    build:
      context: "./"
      dockerfile: "backend.df"
    container_name: "backend"
    environment:
      - DB_CONTAINER_NAME
    networks:
      - "backend_bridge"
      - "backend_db_bridge"
    depends_on:
      - "db"
    #ports:
    #  - 4000:4000
  #
  db:
    build:
      context: "./"
      dockerfile: db.df
    container_name: $DB_CONTAINER_NAME
    networks:
      - "backend_db_bridge"
    volumes:
      - "cass-shared:/var/lib/cassandra/data"

networks:
  frontend_bridge:
    driver: "bridge"
    attachable: true

  backend_bridge:
    driver: "bridge"
    attachable: true

  backend_db_bridge:
    driver: "bridge"
    attachable: true

volumes:
  cass-shared:
    driver: "local"
    name: "cass-shared"
