version: "3.9"
services:
  rev_proxy:
    build:
      context: "./"
      dockerfile: "nginx.df"
    container_name: "rev_proxy"
    ports:
      - "80:80"
    networks:
      - "frontend_bridge"
      - "backend_bridge"
    depends_on:
      - "frontend"
      - "backend"

  frontend:
    build:
      context: "./"
      dockerfile: "frontend.df"
    container_name: "frontend"
    networks:
      - "frontend_bridge"
    expose:
      - "3000"

  backend:
    build:
      context: "./"
      dockerfile: "backend.df"
    container_name: "backend"
    deploy:
      resources:
        limits:
          memory: "300M"
    environment:
      - DB1_NAME
      - DB2_NAME
    networks:
      - "backend_bridge"
      - "db_cluster"
    depends_on:
      - "db2"
    secrets:
      - db_pass
      - db_user
    expose:
      - "4000"

  db1:
    image: "bitnami/cassandra:latest"
    container_name: $DB1_NAME
    networks:
      - "db_cluster"
    environment:
      - CASSANDRA_SEEDS
      - CASSANDRA_CLUSTER_NAME
    volumes:
      - "cluster-storage:$CASSANDRA_STORAGE_PATH"
      - "$CQL_SCRIPTS_PATH:$CASSANDRA_SCRIPTS_PATH"
    expose:
      - 7000
      - 9042
    deploy:
      resources:
        limits:
          memory: 4G

  db2:
    image: "bitnami/cassandra:latest"
    container_name: $DB2_NAME
    networks:
      - "db_cluster"
    environment:
      - CASSANDRA_SEEDS
      - CASSANDRA_CLUSTER_NAME
    expose:
      - 7000
      - 9042
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  frontend_bridge:
    driver: "bridge"
    attachable: true

  backend_bridge:
    driver: "bridge"
    attachable: true

  db_cluster:
    driver: "bridge"
    attachable: true

volumes:
  cluster-storage:
    driver: "local"
    name: "cluster-storage"

secrets:
  db_pass:
    file: "./secrets/db_pass.txt"
  db_user:
    file: "./secrets/db_user.txt"
